package npcs;

import java.lang.reflect.InvocationTargetException;
import java.util.HashMap;

import engine.GameObject;
import network.NetworkHandler;

public class NPC extends GameObject {
	
	private String npcType;
	
	private static HashMap<Integer, NPC> npcMap;
	
	public NPC () {
		npcType = getClass ().getSimpleName ();
		initNpc ();
	}
	
	public NPC (String type) {
		this.npcType = type;
		initNpc ();
	}
	
	public void initNpc () {
		if (NetworkHandler.isHost ()) {
			declare (0, 0);
			NetworkHandler.getServer ().sendMessage ("NPC CREATE " + toString ());
		}
	}
	
	/**
	 * Makes a new instance of the NPC specified by the string s (in the format generated by toString())
	 * @param s the string containing the NPC parameters
	 * @return a new NPC with the type specified in s, with all the parameters specified in s
	 */
	public static NPC getInstance (String s) {
		String[] params = s.split (":");
		try {
			//Make and return a new NPC with the given parameters
			NPC newNpc = (NPC) Class.forName ("npcs." + params[0]).getConstructor ().newInstance ();
			newNpc.id = Integer.parseInt (params [1]);
			newNpc.updateNpc (s);
			return newNpc;
		} catch (InstantiationException | IllegalAccessException | IllegalArgumentException | InvocationTargetException
				| NoSuchMethodException | SecurityException | ClassNotFoundException e) {
			//Return null if instantiation fails
			return null;
		}
	}
	
	/**
	 * Updates the parameters of this NPC to match the String s
	 * @param s the parameter string (of the format output by toString())
	 */
	public void updateNpc (String s) {
		String[] params = s.split (":");
		this.id = Integer.parseInt (params [1]);
		setX (Double.parseDouble (params [2]));
		setY (Double.parseDouble (params [3]));
	}
	
	/**
	 * Only call as host, updates position for clients
	 * @param y
	 */
	public void assertPosition (double x, double y) {
		setX (x);
		setY (y);
		NetworkHandler.getServer ().sendMessage ("NPC UPDATE " + toString ());
	}
	
	/**
	 * Gets the type of this NPC as a String
	 * @return this NPC's type
	 */
	public String getNpcType () {
		return npcType;
	}
	
	/**
	 * Use instead of frameEvent for NPC types
	 */
	public void npcFrame () {
		//Do nothing
	}
	
	public static NPC getNpcById (int id) {
		return npcMap.get (id);
	}
	
	private void mapNpc () {
		if (npcMap == null) {
			npcMap = new HashMap<Integer, NPC> ();
		}
		npcMap.put (getId (), this);
	}
	
	@Override
	public void declare () {
		declare (0, 0);
		mapNpc ();
	}
	
	@Override
	public void declare (int x, int y) {
		if (!NetworkHandler.isHost ()) {
			int currId = id;
			super.declare (x, y);
			id = currId; //Hacky workaround to keep the old ID
		} else {
			super.declare (x, y);
		}
		mapNpc ();
	}
	
	@Override
	public void forget () {
		super.forget ();
		if (NetworkHandler.isHost ()) {
			NetworkHandler.getServer ().sendMessage ("NPC FORGET " + getId ());
		}
	}
	
	@Override
	public void frameEvent () {
		if (NetworkHandler.isHost ()) {
			npcFrame ();
		}
	}
	
	@Override
	public String toString () {
		//If overriding, append to super.toString()
		return getNpcType () + ":" + getId () + ":" + getX () + ":" + getY ();
	}

}
